language: node_js
node_js:
  - "6.9.4"
#services:
#  - mongodb

notifications:
  email: false
  
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g nodeunit
  - npm install tobi
  - npm install soda
#  - mongo mydb_test --eval 'db.addUser("travis", "test");'